"""Unit-тесты на probe.log: redact() и ProbeLogger.

Критично: secrets (Bearer JWT) НЕ ДОЛЖНЫ попадать в файлы логов.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest
from probe.log import ProbeLogger, _redact


class TestRedact:
    def test_redacts_authorization_key(self) -> None:
        out = _redact({"Authorization": "Bearer eyJ.SECRET", "other": "ok"})
        assert out["Authorization"] == "***REDACTED***"
        assert out["other"] == "ok"

    def test_redacts_lowercase_authorization(self) -> None:
        out = _redact({"authorization": "Bearer x"})
        assert out["authorization"] == "***REDACTED***"

    def test_redacts_token_keys(self) -> None:
        out = _redact({"token": "vooi_xxx", "jwt": "abc", "X-Token": "y"})
        assert out["token"] == "***REDACTED***"
        assert out["jwt"] == "***REDACTED***"
        assert out["X-Token"] == "***REDACTED***"

    def test_redacts_recursively_in_nested_dict(self) -> None:
        out = _redact({"req": {"headers": {"Authorization": "Bearer SECRET"}, "body": "ok"}})
        assert out["req"]["headers"]["Authorization"] == "***REDACTED***"
        assert out["req"]["body"] == "ok"

    def test_redacts_in_list_items(self) -> None:
        out = _redact([{"token": "x"}, {"y": 1}])
        assert out[0]["token"] == "***REDACTED***"
        assert out[1] == {"y": 1}

    def test_does_not_alter_non_secret_values(self) -> None:
        d = {"a": 1, "b": "foo", "c": [1, 2, 3]}
        assert _redact(d) == d

    def test_redaction_does_search_in_values_after_4_1_fix(self) -> None:
        # §4.1 fix: regex post-pass на VALUES (Bearer/JWT/vooi_) — больше не gap.
        d = {"raw_response": "Authorization: Bearer eyJ.SECRET"}
        out = _redact(d)
        assert "SECRET" not in out["raw_response"]
        assert "***REDACTED***" in out["raw_response"]

    def test_redaction_masks_naked_jwt_in_value(self) -> None:
        d = {"observed": "stream returned eyJabc.def.ghi token"}
        out = _redact(d)
        assert "eyJabc" not in out["observed"]

    def test_redaction_masks_vooi_token_in_value(self) -> None:
        d = {"trace": "using vooi_abc1234567 for read-only"}
        out = _redact(d)
        assert "vooi_abc1234567" not in out["trace"]

    def test_redaction_preserves_non_secret_strings(self) -> None:
        d = {"msg": "hello world without secrets"}
        assert _redact(d) == d


class TestProbeLogger:
    def test_creates_run_dir_on_init(self, tmp_path: Path) -> None:
        log = ProbeLogger(run_id="test123", runs_dir=tmp_path)
        assert (tmp_path / "test123").is_dir()
        assert log.run_dir == tmp_path / "test123"

    def test_log_writes_ndjson_line(
        self,
        tmp_path: Path,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        log = ProbeLogger(run_id="r1", runs_dir=tmp_path)
        log.log("EVENT_X", k="v", n=42)
        captured = capsys.readouterr()
        assert captured.out.endswith("\n")
        line = json.loads(captured.out.strip())
        assert line["event"] == "EVENT_X"
        assert line["k"] == "v"
        assert line["n"] == 42
        assert line["run_id"] == "r1"
        assert "ts" in line

    def test_log_redacts_secrets_in_stdout_and_file(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        log = ProbeLogger(run_id="r2", runs_dir=tmp_path)
        log.log("AUTH_TEST", token="vooi_super_secret_xxx")
        out = capsys.readouterr().out
        assert "vooi_super_secret_xxx" not in out
        assert "***REDACTED***" in out

        events_file = tmp_path / "r2" / "events.ndjson"
        assert events_file.exists()
        content = events_file.read_text()
        assert "vooi_super_secret_xxx" not in content
        assert "***REDACTED***" in content

    def test_write_artifact_redacts_dict(self, tmp_path: Path) -> None:
        log = ProbeLogger(run_id="r3", runs_dir=tmp_path)
        path = log.write_artifact("data.json", {"Authorization": "Bearer X", "k": "v"})
        loaded = json.loads(path.read_text())
        assert loaded["Authorization"] == "***REDACTED***"
        assert loaded["k"] == "v"

    def test_run_id_autogenerated_if_not_supplied(self, tmp_path: Path) -> None:
        log = ProbeLogger(runs_dir=tmp_path)
        assert log.run_id is not None
        assert len(log.run_id) == 8  # uuid.uuid4().hex[:8]
